### ISSUE TITLE
코인 충전 페이지 기능을 DB와 연동하고 결제 내역을 UI로 표시한다. 

### ISSUE THREAD

**Issue by zldnlto** [FRONTENDSCHOOLPLUS2/HighlighTalk#103]
### 📄 Describe

<img width="400" alt="스크린샷 2024-08-22 오후 12 12 13" src="https://github.com/user-attachments/assets/3789a790-5e86-4794-b2be-8d36e1b0c540">

코인 충전 페이지 기능 DB 송수신 처리 

### ✅ Tasks

- [x]  테스트 결제 후 받아오는 객체 정보를 이용하여 DB order 컬렉션에 결제 내역을 POST한다 -> DB 요구사항 고려하여 replies 컬렉션으로 변경
- [x]  DB 데이터와 세션 정보의 무결성을 위해 결제 절차를 캡슐화한다 
- [x] 결제 내역별 Item UI 구현, order 정보 받아서 화면에 표시  

### 🙋🏻 More

화이팅
