### ISSUE TITLE
인트로 페이지 마무리 작업을 진행한다.

### ISSUE THREAD

**Issue by woojoung1217** [FRONTENDSCHOOLPLUS2/HighlighTalk#116]
### ✅ Tasks

- [ ]  인트로 페이지 Ui 구현
- [ ]  파일 업로드 페이지 설명 추가
- [ ]  메인 페이지 이미지 변경 

### 🙋🏻 More
*No response*
