### ISSUE TITLE
내 분석 보관함의 제목 편집과 항목 삭제 기능을 구현한다.

### ISSUE THREAD

**Issue by yeodahui** [FRONTENDSCHOOLPLUS2/HighlighTalk#122]
### 📄 Describe

내 분석 보관함의 제목 편집 및 항목 삭제 기능이 현재 구현되지 않은 상태.
기능을 완성해야 함

<img width="600" alt="image" src="https://github.com/user-attachments/assets/20a1d6fb-14aa-4469-8866-1eade60fa92d">

### ✅ Tasks

- [ ]  메뉴 버튼 클릭 시 select box 사용할 것인지 bottom / modal 사용할 것인지 결정
- [ ]  제목 편집 기능 구현
- [ ] 항목 삭제 기능 구현
- [ ] freetest / lovetest 라우팅 잘 되는지 확인

### 🙋🏻 More
*No response*
