### ISSUE TITLE
유료테스트 결제 기능 구현과 배포 전 변경사항 수정을 진행한다. 

### ISSUE THREAD

**Issue by zldnlto** [FRONTENDSCHOOLPLUS2/HighlighTalk#126]
### 📄 Describe

유료테스트 결제 기능구현, 배포 전 피드백 반영

### ✅ Tasks

- [x] lovetest 진행하려면 결제 진행하도록 구현 
- [x] 프로필 사진 에러 해결
- [x]  사이드바 선택범위 늘리기
- [x] 사이드바 아이콘 / 내용 채우기 
- [x] NavBar 메뉴 고치기 (-> 홈, 커뮤니티, 보관함, 코인충전) 
- [x] 마이페이지 분석 결과 없을 경우 
- [x] 결제내역 DB 올리기 에러 수정 
- [x] 회원가입 축하 모달 > 분석하러 가기 에러 ( 모달 안닫힘 ) 

### 🙋🏻 More

불살라 ~
