### ISSUE TITLE
유료테스트의 결제 모달 게스트 상태 예외처리, 피드백 사항 수정을 진행한다. 

### ISSUE THREAD

**Issue by zldnlto** [FRONTENDSCHOOLPLUS2/HighlighTalk#131]
### 📄 Describe

모달 비동기 이슈 (우중님 도움 받아 해결) 
유료테스트의 결제 모달 게스트 상태 예외처리, 피드백 사항 수정을 진행한다. 

### ✅ Tasks

- [x]  모달 비동기 이슈
- [x]  담당 페이지 화면 줄었을 때 `margin-top`필요해보이는 부분 확인 
- [x]  마이페이지 내 분석 보관함 클릭 시 결과 이동, 보관함 페이지로 라우팅 
- [x]  프로필 사진 에러 해결

### 🙋🏻 More
