### ISSUE TITLE
유료페이지 결제 모달 수정사항을 작업한다. 

### ISSUE THREAD

**Issue by zldnlto** [FRONTENDSCHOOLPLUS2/HighlighTalk#143]
### 📄 Describe

유료페이지 결제 모달 수정사항을 작업한다.
+ 인트로 페이지의 안내 이미지 변경 

### ✅ Tasks

- [x]  게스트인 경우 로그인 페이지로 안내 내용이 떠야 함 
- [x]  setCurrentStep의 동작 에러 해결 
- [x] 타입 에러 체크, 동작 되는지 5번 시도 
- [ ] 마이페이지 결과 분석 보관함 수정
- [ ] 결제 내역 페이지 사용 내역 불러오기 에러 수정 

### 🙋🏻 More
*No response*
