### ISSUE TITLE
토큰 수를 셀 수 있는 라이브러리를 탐색하고 테스트한다.

### ISSUE THREAD

**Issue by yeodahui** [FRONTENDSCHOOLPLUS2/HighlighTalk#21]
### 📄 Describe
- chat GPT에 요청을 보내는 데이터의 토큰 수를 제한하기 위해 토큰 수 측정이 필요
- chat GPT 모델 별 토큰 수를 계산하는 라이브러리 [tiktoken](https://github.com/dqbd/tiktoken), gpt-tokenizer
- 토큰 수 측정에 의미있는 결과를 내는지, 안정적으로 동작하는 지 모듈을 만들어 테스트

### ✅ Tasks

- [ ] tiktoken 라이브러리 ReadMe를 읽고 모듈 만들기
- [ ] gpt-tokenizer 라이브러리 ReadMe를 읽고 모듈 만들기
- [ ] 다른 작업자가 코드를 해석해 사용할 수 있도록 신경써서 주석을 달기
- [ ] tiktoken, gpt-tokenizer 결과 비교하기

### 🙋🏻 More
*No response*

**Comment by zldnlto** [comment]
다히님 빠른 테스트 아주 나이스에요 나주 아이스~!
