### ISSUE TITLE
FileUploader페이지에서 함수로직을 작성한다.

### ISSUE THREAD

**Issue by woojoung1217** [FRONTENDSCHOOLPLUS2/HighlighTalk#33]
### 📄 Describe
FileUploader페이지에서 함수로직을 작성하고 이전 테스트에서 사용하던 불 필요한 함수 들을 삭제한다.
재사용 가능하도록 함수 명을 fetchData => gpt 로 변경한다.
css파일 변수 등록 , css파일명 _ 추가 

### ✅ Tasks

- [x]  함수 분리 및 삭제
- [x]  함수명 변경 
- [x]  css 파일 변수 등록
- [x]  css 파일명 변경

### 🙋🏻 More
*No response*
