### ISSUE TITLE
분석 결과 페이지의 그래프 요소를 구현한다.

### ISSUE THREAD

**Issue by yeodahui** [FRONTENDSCHOOLPLUS2/HighlighTalk#34]
### 📄 Describe

분석 결과 페이지 중 그래프 형태로 표현할 수 있는 요소들을 화면에 구현한다.
d3와 chart.js 라이브러리 중 어떤 라이브러리가 적합할 지 탐색하고 구현 요소에 적합한 그래프를 선택해 더미 데이터로 구현해본다.

[1. 가장 많이 말 한 사람]

<img width="448" alt="image" src="https://github.com/user-attachments/assets/cc970d0c-b681-4579-8934-d685f2f5d808">

[2. 가장 많이 나온 단어]

<img width="507" alt="image" src="https://github.com/user-attachments/assets/8ace7632-c921-4ad3-a3c4-929d37e7bd40">

### ✅ Tasks

- [x] chart.js와 d3 비교 및 사용할 라이브러리 선택
- [x] 각 구현 요소에 알맞는 그래프 선택
- [x] 결과 페이지에 구현

### 🙋🏻 More
*No response*
