### ISSUE TITLE
회원가입, 로그인 기능을 구현한다.

### ISSUE THREAD

**Issue by zldnlto** [FRONTENDSCHOOLPLUS2/HighlighTalk#36]
### 📄 Describe
`/signup` 페이지 작업 
사이트 기본 회원가입 기능 구현 

### ✅ Tasks

- [x] react-hook-form 을 이용한 유효성 검사 
- [x] 이메일 중복 체크 
- [x] 회원가입 기능   
- [x] NextAuth를 통한 로그인 구현 
- [ ] 소셜 로그인 (구글) 

### 🙋🏻 More

로그인만 NextAuth이고 회원가입 일반 React 코드로 구현되어 있는데, NextAuth를 통한 회원가입 기능 추후 이슈 작성해서 수정 예정입니다 
++ 소셜 로그인 확장
