### ISSUE TITLE
로그인, 회원가입 기능을 보완한다.

### ISSUE THREAD

**Issue by zldnlto** [FRONTENDSCHOOLPLUS2/HighlighTalk#38]
### 📄 Describe

로그인, 회원가입 기능 보완

### ✅ Tasks

- [x]  회원가입 serverActions 처리
- [x]  user session에 coin 항목 추가
- [x] 소셜 로그인 추가 지원 (깃허브, 카카오)
- [x] 소셜 로그인 token 처리
- [x] 소셜 로그인 유저 정보 DB에 저장

### 🙋🏻 More

- 재사용된 친환경 이슈입니다 .. ㅋㅋ  원래 Modal 관련 이슈였는데 프로젝트 진행상의 편의 봐서 우중님께 넘겼습니다 (thanks)
