### ISSUE TITLE
데이터패칭이 서버에서 실행되도록 하고 드래그 앤 드롭 기능을 구현한다.

### ISSUE THREAD

**Issue by woojoung1217** [FRONTENDSCHOOLPLUS2/HighlighTalk#43]
### 📄 Describe
- 라우트 핸들러 사용으로 변경
- 코드 스플리팅으로 재사용성 및 성능 향상 
- 파일 드래그 앤 드롭 기능 구현 

### ✅ Tasks

- [x]  데이터 페칭 함수가 컴포넌트에서 실행되는 상황이였는데 이 경우 API_KEY가 노출 될 위험이 있어 라우트 핸들러로 처리 
- [x]  새로운 파일 구조 생성 api>generate> route 
- [x]  파일 드래그 앤 드롭 기능 구현 

### 🙋🏻 More
*No response*
