### ISSUE TITLE
분석 결과 페이지 UI를 구현한다.

### ISSUE THREAD

**Issue by yeodahui** [FRONTENDSCHOOLPLUS2/HighlighTalk#52]
### 📄 Describe

분석 결과 페이지의 UI 구현

### ✅ Tasks

- [ ]  라우트 및 레이아웃 설정
- [ ]  대화내용 요약 UI 구현
- [ ] 가장 많이 말 한 사람 UI 구현
- [ ]  MBTI UI 컴포넌트 구현 X -> 영역만 잡아놓기
- [ ] 가장 많이 나온 단어 UI 구현
- [ ] 공유하기 버튼

### 🙋🏻 More
- 공유하기 기능에 관해 추가 기획 필요
-
