### ISSUE TITLE
Gpt api 최적화 및 테마 아이템을 구현하고 테스트 파일을 폴더 하나에 관리한다.

### ISSUE THREAD

**Issue by woojoung1217** [FRONTENDSCHOOLPLUS2/HighlighTalk#57]
### ✅ Tasks

- [x]  api 최적화 시도
- [x]  테마 상품 구현 (env)
- [x]  freetest / lovetest => (tests) = > [ freetest , lovetest ] 로 이동
- [x] 버튼 컴포넌트 변경으로 사용 부분 변경 

### 🙋🏻 More
*No response*
