### ISSUE TITLE
데이터를 서버에 저장하고 조회한다.

### ISSUE THREAD

**Issue by woojoung1217** [FRONTENDSCHOOLPLUS2/HighlighTalk#63]
### ✅ Tasks

- [x]  데이터 패치 이 후 서버에 저장 되는 통신을 한번 더 만든다.
- [x]  파일을 분리해 결과 페이지를 생성한다
- [x] 모달, 모달 스토어를 생성한다.

### 🙋🏻 More
*No response*

**Comment by woojoung1217** [comment]
나 짱
