### ISSUE TITLE
결과를 바탕으로 인물 별 Mbti 컴포넌트를 만든다.

### ISSUE THREAD

**Issue by woojoung1217** [FRONTENDSCHOOLPLUS2/HighlighTalk#65]
### ✅ Tasks

- [x]  Mbti 컴포넌트 구현 
- [x]  Mbti 16개 이미지 추가 
- [x] 폰트 최적화를 위해 폰트 변경 시도
- [x] 로딩 구현을 위한 react-spinner 전역에 설치
- [x] 로딩 컴포넌트 구현 

### 🙋🏻 More
*No response*
