### ISSUE TITLE
Next-Auth를 활용한 접근 제어 및 테스트 페이지 보안 강화 기능을 구현한다. 

### ISSUE THREAD

**Issue by zldnlto** [FRONTENDSCHOOLPLUS2/HighlighTalk#73]
### 📄 Describe
next-auth middleware를 이용한 접근 제어 기능 구현

제어가 필요한 페이지들은 아래와 같음
- 마이 페이지
- 코인 충전 페이지 
- test 페이지들 라우트로 접근 못하도록 
  - 게스트 상태에서 test 페이지 클릭 시 모달 띄워서 로그인 유도 

- 로그인된 상태에서 로그인/회원가입 페이지 접근 제어 (완료) 
+) 테스트 로그인 버튼도 함께 추가하겠습니다 

### ✅ Tasks

- [x]  테스트 로그인 버튼을 추가한다. 
- [x]  마이페이지, 코인 충전 페이지 접근시 유저 권한 확인 
- [x]  게스트일 경우 무료 test 페이지 접근 X 
- [ ] #77

### 🙋🏻 More

유료 test도 결제한 유저들만 접근 가능하도록 해야하는데, 테스트에 대한 결제내역은 order 컬렉션 사용할 예정 
1. 요청 시 DB/order와 대조하여 결제내역 확인(middleware)  
2. 세션에 유저가 접근할 수 있는 콘텐츠 ID 목록을 추가 (컨텐츠 ID 필요) 

두 가지 방법 중 가려볼까 합니다

이밖에 접근 제어요소 더 있으면 이 밑으로 댓글댓글미
