### ISSUE TITLE
분석 결과 보관함을 구현한다.

### ISSUE THREAD

**Issue by yeodahui** [FRONTENDSCHOOLPLUS2/HighlighTalk#84]
### 📄 Describe

내가 수행했던 분석 결과들을 확인할 수 있는 분석 결과 보관함 페이지를 구현한다.

<img width="770" alt="image" src="https://github.com/user-attachments/assets/19c62666-cf5b-45dc-a1d6-6f3087ea78e6">

- 수행한 분석에 대해서 조회 / 삭제가 가능해야 한다.
- 삭제할 경우 "정말 삭제하시겠습니까? 삭제한 데이터는 다시 복구할 수 없습니다" 문구 출력
- 수행한 분석의 title에 대한 수정이 가능해야 한다. (+ 새로 등록 시 title 자동 생성)
- 분석을 수행한 사람의 이름, 대화 참여자가 확인 가능해야 한다.
- 분석 테마가 보여야 한다.
- 클릭하면 연결된 분석결과 페이지로 이동한다.
- (추후 구현사항)내가 생성한 분석 결과와 다른 사람으로부터 공유받은 분석 결과를 함께 확인할 수 있다.(공유받은 결과는 수정/삭제 불가)

### ✅ Tasks

- [x] 분석 결과 보관함 페이지 디자인
- [x] 데이터 생성 시 title 자동 입력
- [x] UI 컴포넌트 만들기
- [x] post 컬렉션 데이터 내 분석 테마 저장할 공간 정하기(회의)
- [ ] 분석 결과 조회 / 삭제 / 수정(제목수정)
- [ ] 삭제 Modal

### 🙋🏻 More
*No response*
